//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resotel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bedroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bedroom()
        {
            this.booking = new HashSet<booking>();
            this.feature = new HashSet<feature>();
        }
    
        public int bedroom_number { get; set; }
        public int bedroom_floor { get; set; }
        public string bedroom_status { get; set; }
        public int bedroom_type_id { get; set; }
    
        public virtual bedroom_type bedroom_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feature> feature { get; set; }
    }
}
