//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resotel.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class resotelEntities : DbContext
    {
        public resotelEntities()
            : base("name=resotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bedroom> bedroom { get; set; }
        public virtual DbSet<bedroom_type> bedroom_type { get; set; }
        public virtual DbSet<booking> booking { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<concern> concern { get; set; }
        public virtual DbSet<feature> feature { get; set; }
        public virtual DbSet<invoice> invoice { get; set; }
        public virtual DbSet<promotion> promotion { get; set; }
        public virtual DbSet<rate> rate { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
