//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resotel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string user_identifiant { get; set; }
        public string user_password { get; set; }
        public string user_lastname { get; set; }
        public string user_firstname { get; set; }
        public string role_name { get; set; }
    
        public virtual role role { get; set; }
    }
}
